//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTC_THANHPHAN
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<long> NGUOISUA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> ITEM_LEVEL { get; set; }
        public string CODE { get; set; }
        public Nullable<bool> IS_BANQUANLY { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<int> THUTU { get; set; }
        public Nullable<bool> CAN_SEND_SMS { get; set; }
    }
}
