//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAT_GROUP_USER
    {
        public long ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
    }
}
