//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DANHMUC_DATA_VAITRO
    {
        public int ID { get; set; }
        public Nullable<int> DATA_ID { get; set; }
        public Nullable<int> VAITRO_ID { get; set; }
    }
}
