//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DANHMUC_DATA
    {
        public int ID { get; set; }
        public Nullable<int> DM_NHOM_ID { get; set; }
        public string TEXT { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> DATA { get; set; }
        public string COLOR { get; set; }
        public string ICON { get; set; }
        public Nullable<int> DEPTID { get; set; }
        public string CODE { get; set; }
    }
}
