//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NGUOIDUNG_THAOTAC
    {
        public long DM_NGUOIDUNG_THAOTAC_ID { get; set; }
        public Nullable<long> DM_NGUOIDUNG_ID { get; set; }
        public Nullable<long> DM_THAOTAC { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOISUA { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    }
}
