//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFILE_CHIASE
    {
        public long ID { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public Nullable<System.DateTime> NGAY_CHIASE { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public Nullable<bool> IS_FOLDER { get; set; }
        public string GHICHU { get; set; }
        public Nullable<long> SHARING_BY { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
        public Nullable<int> PERMISSION { get; set; }
    }
}
