//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSO_CANBO_QUATRINH_LUONG
    {
        public long ID { get; set; }
        public Nullable<long> HOSO_ID { get; set; }
        public string THANG_NAM { get; set; }
        public string MANGACH_BAC { get; set; }
        public string HESOLUONG { get; set; }
    
        public virtual HOSO_CANBO_THONGTINCHUNG HOSO_CANBO_THONGTINCHUNG { get; set; }
    }
}
