//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSO_CANBO_CONGTAC
    {
        public long ID { get; set; }
        public long HOSO_ID { get; set; }
        public string THOIGIANCONGTAC { get; set; }
        public string CHUCDANHDONVI { get; set; }
    
        public virtual HOSO_CANBO_THONGTINCHUNG HOSO_CANBO_THONGTINCHUNG { get; set; }
    }
}
