//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSO_CANBO_DAOTAO
    {
        public long ID { get; set; }
        public long HOSO_ID { get; set; }
        public string TENTRUONG { get; set; }
        public string CHUYENNGANHDAOTAO { get; set; }
        public string THOIGIANDAOTAO { get; set; }
        public string HINHTHUCDAOTAO { get; set; }
        public string VANBANGCHUNGCHI { get; set; }
    
        public virtual HOSO_CANBO_THONGTINCHUNG HOSO_CANBO_THONGTINCHUNG { get; set; }
    }
}
