//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_VANBANDI_TRAODOI
    {
        public long ID { get; set; }
        public Nullable<long> VANBANDI_ID { get; set; }
        public string NOIDUNGTRAODOI { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
    }
}
