//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_CONGVIEC_XINLUIHAN
    {
        public long ID { get; set; }
        public Nullable<long> CONGVIEC_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string BUTPHELANHDAO { get; set; }
        public Nullable<bool> IS_APPROVED { get; set; }
        public Nullable<bool> IS_SENDREQUEST { get; set; }
        public Nullable<System.DateTime> HANKETHUC { get; set; }
        public Nullable<System.DateTime> HANKETTHUCTRUOC { get; set; }
        public Nullable<System.DateTime> NGAYGUI { get; set; }
        public Nullable<System.DateTime> NGAYPHEDUYET { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOIPHEDUYET { get; set; }
        public Nullable<System.DateTime> HANKETTHUC_LANHDAODUYET { get; set; }
    }
}
