//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_VANBANDEN_DONVINHAN
    {
        public long ID { get; set; }
        public Nullable<long> VANBANDEN_ID { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
    }
}
