//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_VANBANDEN
    {
        public long ID { get; set; }
        public Nullable<int> DOKHAN_ID { get; set; }
        public Nullable<int> LINHVUCVANBAN_ID { get; set; }
        public Nullable<int> LOAIVANBAN_ID { get; set; }
        public string NGUOIKY { get; set; }
        public string CHUCVU { get; set; }
        public string TRICHYEU { get; set; }
        public string NOIDUNG { get; set; }
        public string SOHIEU { get; set; }
        public Nullable<int> SOTRANG { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<long> NGUOISUA { get; set; }
        public Nullable<int> DOMAT_ID { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
        public Nullable<long> VANBANDI_ID { get; set; }
        public Nullable<System.DateTime> NGAY_HIEULUC { get; set; }
        public Nullable<System.DateTime> NGAYHET_HIEULUC { get; set; }
        public Nullable<System.DateTime> NGAY_VANBAN { get; set; }
        public Nullable<System.DateTime> NGAY_BANHANH { get; set; }
        public Nullable<bool> HAS_SIGNED { get; set; }
        public Nullable<bool> IS_NOIBO { get; set; }
        public Nullable<int> SOVANBANDEN_ID { get; set; }
        public string SODITHEOSO { get; set; }
        public Nullable<System.DateTime> NGAYCONGTAC { get; set; }
        public Nullable<int> GIO_CONGTAC { get; set; }
        public Nullable<int> PHUT_CONGTAC { get; set; }
        public Nullable<int> SODITHEOSO_NUMBER { get; set; }
        public string VANBANLIENQUAN { get; set; }
        public string MA_DANGKY { get; set; }
        public Nullable<int> LOAI_COQUAN_ID { get; set; }
        public Nullable<int> SO_BAN { get; set; }
        public Nullable<int> THONGTIN_LOAI_ID { get; set; }
        public string TACGIA { get; set; }
        public Nullable<int> CONGVAN_DEN_ID { get; set; }
        public Nullable<System.DateTime> HAN_GIAIQUYET { get; set; }
        public Nullable<System.DateTime> THOIHAN_GIAIQUYET { get; set; }
        public string NGUOINHAN_TRUCTIEP_IDS { get; set; }
    }
}
