//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_CONGVIEC_NGUOITHAMGIAXULY
    {
        public long ID { get; set; }
        public Nullable<long> CONGVIEC_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
    }
}
