//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_CAPNHATTIENDO_CV
    {
        public long ID { get; set; }
        public Nullable<long> CONGVIEC_ID { get; set; }
        public Nullable<int> TIENDOCONGVIEC { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHATTIENDO { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string NOIDUNG { get; set; }
        public string NGUOITAO { get; set; }
    }
}
