//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_SUBTASK
    {
        public long ID { get; set; }
        public Nullable<long> CONGVIEC_ID { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<int> TRANGTHAI_ID { get; set; }
        public Nullable<int> MUCDOUUTIEN { get; set; }
        public Nullable<int> DOKHAN { get; set; }
        public Nullable<System.DateTime> NGAYHOANTHANH { get; set; }
        public Nullable<bool> DAGIAOVIEC { get; set; }
        public Nullable<System.DateTime> HANHOANTHANH { get; set; }
        public Nullable<bool> IS_HASPLAN { get; set; }
    }
}
