//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCV_CONGVIEC
    {
        public long ID { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public string ITEMTYPE { get; set; }
        public string TENCONGVIEC { get; set; }
        public string NOIDUNGCONGVIEC { get; set; }
        public Nullable<System.DateTime> NGAY_NHANVIEC { get; set; }
        public Nullable<System.DateTime> NGAYHOANTHANH_THEOMONGMUON { get; set; }
        public Nullable<int> DOUU_TIEN { get; set; }
        public Nullable<int> DOKHAN { get; set; }
        public Nullable<int> TRANGTHAI_ID { get; set; }
        public Nullable<bool> IS_POPUP { get; set; }
        public Nullable<bool> IS_MESG { get; set; }
        public Nullable<bool> IS_EMAIL { get; set; }
        public Nullable<bool> IS_SMS { get; set; }
        public Nullable<bool> HAS_NHACVIECDENHAN { get; set; }
        public Nullable<int> SONGAYNHACTRUOCHAN { get; set; }
        public Nullable<int> HAS_FILE { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<int> PHANTRAMHOANTHANH { get; set; }
        public Nullable<long> CONGVIECGOC_ID { get; set; }
        public Nullable<long> NGUOIXULYCHINH_ID { get; set; }
        public Nullable<bool> IS_SUBTASK { get; set; }
        public Nullable<long> SUBTASK_ID { get; set; }
        public Nullable<bool> DATUDANHGIA { get; set; }
        public Nullable<bool> NGUOIGIAOVIECDANHGIA { get; set; }
        public Nullable<int> PHANTRAMHOANTHANH_OLD { get; set; }
        public Nullable<bool> NGUOIGIAOVIECDAPHANHOI { get; set; }
        public Nullable<bool> IS_HASPLAN { get; set; }
        public Nullable<bool> IS_MYJOB { get; set; }
        public Nullable<long> NGUOIGIAOVIEC_ID { get; set; }
        public Nullable<System.DateTime> NGAYDUYET { get; set; }
        public Nullable<bool> IS_ASSIGNED { get; set; }
        public Nullable<bool> DAGIAOVIEC { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC_THUCTE { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU_THUCTE { get; set; }
        public Nullable<bool> IS_EXTEND_TASK { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU_KEHOACH { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC_KEHOACH { get; set; }
        public Nullable<bool> IS_BATDAU { get; set; }
        public string MUCTIEU_CONGVIEC { get; set; }
        public string CACBUOC_THUCHIEN { get; set; }
        public string NGUOIGIAOVIEC_PHANHOI { get; set; }
        public Nullable<int> XEPLOAICONGVIEC { get; set; }
        public string CONGVIEC_LIENQUAN_ID { get; set; }
        public Nullable<long> VANBANDEN_ID { get; set; }
        public Nullable<long> VANBANDI_ID { get; set; }
    }
}
