//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCONGTAC
    {
        public long ID { get; set; }
        public string TIEUDE { get; set; }
        public System.DateTime NGAY_CONGTAC { get; set; }
        public int GIO_CONGTAC { get; set; }
        public int PHUT_CONGTAC { get; set; }
        public string DIADIEM { get; set; }
        public string GHICHU { get; set; }
        public Nullable<long> NGUOICHUTRI_ID { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<long> NGUOISUA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<bool> IS_LATTEST { get; set; }
        public Nullable<long> LICH_GOC_ID { get; set; }
        public Nullable<long> LANHDAO_ID { get; set; }
    }
}
