//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITAILIEU_THUOCTINH
    {
        public long ID { get; set; }
        public int DANHMUC_ID { get; set; }
        public string TEN_THUOCTINH { get; set; }
        public string MOTA { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    }
}
