//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_DANGKY_XE
    {
        public long ID { get; set; }
        public string TEN_BENHNHAN { get; set; }
        public Nullable<long> CANBO_ID { get; set; }
        public Nullable<int> PHONGBAN_ID { get; set; }
        public Nullable<int> LOAI_CHUYEN_ID { get; set; }
        public Nullable<bool> IS_TUVONG_TRENDUONG { get; set; }
        public Nullable<bool> IS_BHYT { get; set; }
        public Nullable<int> LOAIXE_ID { get; set; }
        public int LOAI_DANGKY_ID { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
        public string MUCDICH { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public Nullable<System.DateTime> NGAY_XUATPHAT { get; set; }
        public Nullable<int> GIO_XUATPHAT { get; set; }
        public Nullable<int> PHUT_XUATPHAT { get; set; }
        public string DIEM_XUATPHAT { get; set; }
        public string DIEM_KETTHUC { get; set; }
        public Nullable<int> SO_NGUOI { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<long> NGUOISUA { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public string LYDO_TUCHOI { get; set; }
        public Nullable<long> LICHCONGTAC_ID { get; set; }
        public Nullable<int> CCTC_THANHPHAN_ID { get; set; }
    }
}
