//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_LAIXE
    {
        public int ID { get; set; }
        public string HOTEN { get; set; }
        public bool GIOITINH { get; set; }
        public string CMND { get; set; }
        public string SODIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<long> NGUOISUA { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<int> CCTC_THANHPHAN_ID { get; set; }
    }
}
