//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_PHONGHOP
    {
        public int ID { get; set; }
        public string TENPHONG { get; set; }
        public string MAPHONG { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> DEPID { get; set; }
        public Nullable<int> SOCHONGOI { get; set; }
    }
}
