//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY_VANBAN
    {
        public long ID { get; set; }
        public string TIEUDE { get; set; }
        public Nullable<long> HOSO_ID { get; set; }
        public string SO_KYHIEU { get; set; }
        public Nullable<int> TOSO { get; set; }
        public Nullable<int> NGONNGU_ID { get; set; }
        public Nullable<System.DateTime> NGAYBANHANH { get; set; }
        public Nullable<int> COQUAN_BANHANH_ID { get; set; }
        public Nullable<int> LINHVUC_ID { get; set; }
        public Nullable<int> LOAI_VANBAN_ID { get; set; }
        public Nullable<int> DOMAT_ID { get; set; }
        public Nullable<int> MUCDO_TRUYCAP { get; set; }
        public Nullable<int> TINHTRANG_VATLY { get; set; }
        public string TRICHYEU_VANBAN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    }
}
