//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY_HOSO
    {
        public long ID { get; set; }
        public string CHUGIAI { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
        public Nullable<int> THOIHAN_BAOQUAN_ID { get; set; }
        public string HOPSO { get; set; }
        public Nullable<int> HOSO_NAM { get; set; }
        public string HOSO_SO { get; set; }
        public Nullable<int> KHO_ID { get; set; }
        public Nullable<int> MUCDO_TRUYCAP { get; set; }
        public string MUCLUC_SO { get; set; }
        public Nullable<int> NAM_CHINHLY { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<int> PHONG_ID { get; set; }
        public string TIEUDE { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string PHONGSO { get; set; }
        public string SOLUONG_TO { get; set; }
        public string FTS { get; set; }
        public string THOIGIAN_TAILIEU { get; set; }
    }
}
