//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY_PHONGHOP
    {
        public int ID { get; set; }
        public long USER_ID { get; set; }
        public int PHONG_ID { get; set; }
        public Nullable<int> GIOBATDAU { get; set; }
        public Nullable<int> GIOKETTHUC { get; set; }
        public string MUCDICH { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> PHUTBATDAU { get; set; }
        public Nullable<int> PHUTKETTHUC { get; set; }
        public Nullable<long> NGUOICHUTRI { get; set; }
        public string THANHPHANTHAMDU { get; set; }
        public string NOIDUNG_XACNHAN { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<int> CCTC_THANHPHAN_ID { get; set; }
    }
}
