//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TINNHAN
    {
        public long ID { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string URL { get; set; }
        public Nullable<long> TO_USER_ID { get; set; }
        public Nullable<long> FROM_USER_ID { get; set; }
        public string TO_USERNAME { get; set; }
        public string FROM_USERNAME { get; set; }
        public Nullable<bool> IS_READ { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<long> NGUOITAO { get; set; }
        public Nullable<long> NOTIFY_ITEM_ID { get; set; }
        public Nullable<int> NOTIFY_ITEM_TYPE { get; set; }
    }
}
