//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAILIEUDINHKEM_VERSION
    {
        public long ID { get; set; }
        public Nullable<long> TAILIEU_ID { get; set; }
        public Nullable<System.DateTime> NGAYTAI { get; set; }
        public string TEN_TAILIEU { get; set; }
        public string VERSION { get; set; }
        public Nullable<long> NGUOITAI { get; set; }
        public string DUONGDAN_FILE { get; set; }
        public string DINHDANG_FILE { get; set; }
        public string MOTA { get; set; }
    }
}
