//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGBAO
    {
        public long ID { get; set; }
        public string MESSAGE { get; set; }
        public string LINK { get; set; }
        public Nullable<long> NGUOI_GUI { get; set; }
        public Nullable<long> NGUOI_NHAN { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<bool> IS_READ { get; set; }
    }
}
