//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUMUC_LUUTRU
    {
        public long ID { get; set; }
        public string TENTHUMUC { get; set; }
        public string THUMUC_AO { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> NGAYXOA { get; set; }
        public Nullable<int> ACCESS_MODIFIER { get; set; }
        public Nullable<int> PERMISSION { get; set; }
        public Nullable<bool> IS_FIXED { get; set; }
        public Nullable<int> PRIOVITY { get; set; }
        public string CLASS { get; set; }
        public Nullable<bool> HAS_FILES { get; set; }
        public Nullable<long> FIXED_FOLDER_ID { get; set; }
    }
}
