//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_PROCESS
    {
        public long ID { get; set; }
        public Nullable<long> ITEM_ID { get; set; }
        public string ITEM_TYPE { get; set; }
        public Nullable<int> WF_ID { get; set; }
        public Nullable<int> CURRENT_STATE { get; set; }
        public string CURRENT_STATE_NAME { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<bool> IS_END { get; set; }
        public Nullable<bool> IS_PENDING { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    }
}
