//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_STEP_CONFIG
    {
        public int ID { get; set; }
        public Nullable<int> WF_STEP_ID { get; set; }
        public Nullable<bool> IS_NOTI_EMAIL { get; set; }
        public Nullable<bool> IS_NOTI_MESSAGE { get; set; }
        public Nullable<bool> IS_NOTI_SMS { get; set; }
        public Nullable<bool> IS_CHANGE_TIME { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<System.DateTime> edit_at { get; set; }
        public Nullable<long> edit_by { get; set; }
        public Nullable<bool> IS_BACK_USER { get; set; }
    }
}
