//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_STEP_USER_PROCESS
    {
        public int ID { get; set; }
        public Nullable<bool> IS_XULYCHINH { get; set; }
        public Nullable<int> VAITRO_ID { get; set; }
        public Nullable<int> CHUCVU_ID { get; set; }
        public Nullable<bool> IS_CUNGPHONG { get; set; }
        public Nullable<bool> IS_CUNGNHANH { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<System.DateTime> edit_at { get; set; }
        public Nullable<long> edit_by { get; set; }
        public Nullable<int> PHONGBAN_ID { get; set; }
        public Nullable<int> LOAIDONVI_ID { get; set; }
        public Nullable<int> WF_STEP_ID { get; set; }
        public string LABEL { get; set; }
    }
}
