//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_USER_REVIEW
    {
        public long ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string ITEMTYPE { get; set; }
        public Nullable<long> ITEMID { get; set; }
        public Nullable<bool> IS_APPROVE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<long> REVIEW_ID { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> REVIEW_AT { get; set; }
    }
}
